#!/usr/bin/python
print("hello");
print("hello");
print("hello");
print("sdsfs");
print("hehe");
print("hehe");
print("hehe");
print("hehe");
print("hehe");
print("hehe");
print("hehe");
print("aasa");
